README.md
args.go
args_test.go
init.go
logger/awslogs/logger.go
logger/buffered_logger.go
logger/common.go
logger/common_test.go
logger/fluentd/logger.go
logger/splunk/logger.go

Add cleanup-time parameter for cleaning up resources like flushing
last few log events to destination after pipes are closed. Default
to 5 seconds and maximum supported value is 12.
This commit also adds unit tests to cover different cleanup time
cases.
`make test` and `make lint` all passed.

Add shim logger cleanup time

---

args.go
debug/debug.go
go.mod
go.sum
logger/awslogs/logger.go
logger/buffered_logger.go
logger/common.go
logger/common_test.go
logger/fluentd/logger.go
logger/splunk/logger.go
main.go

This commit adds delaySeconds option for sending logs to journald before shim
logger process exits.
Also handle error log messages from child go routine and send them to journald
directly rather than simply return it to containerd. Note if container has started to
run, we only send the error message to journald and return nil to containerd. Otherwise
containerd will kill shim process due to error returned from shim logger, and the container
process will exit with code 1 accordingly.

Rework shim logger debugging log messages

---

go.mod
go.sum
logger/awslogs/logger.go
logger/buffered_logger.go
logger/common.go
logger/common_opts.go
logger/common_test.go

**Description of changes:**
This commit add two in-memory buffers with size in bytes based on the chosen log driver.
Replace scanner by bufio.reader to consume bytes from container pipe, and save to the
corresponding buffer. Then scanner our own buffer line by line and send them one by one
to destination. Add two more new test cases in unit test to cover partial log messages
and a single long log message.
This commit also removes LogWithRetry logic as the underlying Log function called from
Docker is running asynchronously and thus retry logic here is meaningless.
**Testing:**
1. `make lint` and `make test`
2. Run one container with one single log message 2 bytes longer than the defined buffer size of log driver, I can see two lines shown up in the destination (CloudWatch, Fluentd and …

Handle long log message

---

logger/common.go

Fixed a bug of splitter logs. The change is made because the underlying docker logger is handling batched log events asynchronously
*Testing*
1. `make test` and `make lint`
2. Manually run container with different combination twslogs driver options multiple times and all worked fine.

Fix a bug of splitted log

---

README.md
args.go
args_test.go
debug/debug.go
go.mod
init.go
logger/common.go
logger/splunk/logger.go
main.go

This change adds the docker config variables as shim logger parameters. The customers can now pass in docker config variables to include container environment, container label, and [container tags](https://docs.docker.com/config/containers/logging/log_tags/) in the log line. 
*Testing*
`make build` and `make test` and `make lint` all pass.
Test alongside with a change on the fargate agent side to pass the docker config to the splunk logdriver, and see that the environment variables, labels, and tags are correctly shown in the log: 
```
{
   attrs: {
     TEST: false 
     TEST2: true 
     TEST3: IDK 
     region: us-east-1 
     service: fargatetest 
   } 
   line: splunk_test_log_0 
   source: stdout 
   tag: docker.io/library/nginx:latest 
} 
```
By submitting …

Add docker config variables to shim logger

---

logger/awslogs/logger.go
logger/buffered_logger.go
logger/buffered_logger_test.go
logger/common.go
logger/fluentd/logger.go
logger/splunk/logger.go

**Description**
Previously in non-blocking mode, the logger was still using scanner
with split function of ScanLines, which will close the reader side
of container pipe if the token is too long for the scanner to handle,
i.e. when a single log message is larger than the size of container pipe,
the reader will crash and stop consuming logs from container pipe. Thus
the container performance will be blocked. This commit resolves this issue.
**What changes have been made**
1. Removed `Scanner.Scan()` function and reuse `Read` function in common.go to read logs from container pipes, But instead of sending logs to final destination when consuming logs from intermediate buffer, it will save each line to the ring buffer by calling `Enqueue`. And the logs sent to final destination in a separate …

Handle long log messages in  non-blocking mode

---

README.md
args.go
init.go
logger/fluentd/logger.go
logger/fluentd/logger_test.go

*Summary*
Adding an option - _sub second precision_ to generate firelens event logs in nanosecond resolution.
This is being enabled to resolve the following request aws/containers-roadmap#839
set option fluentd-sub-second-precision to true.
*Testing*
Code change has been tested on Fargate with Warmpool.

Enabling nanosecond resolution timestamps for firelens

---

logger/buffered_logger.go
logger/common.go
main.go

Previously due to a bug of setuid/setgid syscall in golang, these two syscalls only apply to current goroutine instead of the whole process. With the fix checked in, we are removing the redundant calls of these functions in sub-goroutines.
Note that golang has not included this fix in a specific version, and in order to take it effect, please build shim logger with go built from source.
Golang issue:
https://github.com/golang/go/issues/1435
Golang commit of fix:
https://github.com/golang/go/commit/d1b1145cace8b968307f9311ff611e4bb810710c
1. `make test` and `make lint`
2. Built go from source and use source go built shim logger, run shim logger process with `uid` and `gid` option enabled, I can see process are running with expected UID/GID.
By submitting this pull request, I confirm that …

Modify setuid/setgid syscall and only applies it once in main goroutine

---

args.go
args_test.go
logger/splunk/logger.go
logger/splunk/logger_test.go

1. Pass the value of `SplunkTagKey` to the logging config only if the flag is set, rather than by determining whether the value is not equal to the default (an empty string).
2. This allows passing an empty string as the value of `SplunkTagKey`. Docker does not tag the logs if the specified tag is an empty string; now this functionality will be supported.
An alternative is use a different default value for `SplunkTagKey`, however this means that there will always be one value (the default) that will be ignored if specified by the customer and will result in the default tag `{{.ID}}` being assumed by Docker.
1. `make lint` `make test`
2. Ran shim logger with `--splunk-tag=""` and verified that it is passed to the logging config. Furthermore, ran a container with this tag and the tag as …

Only pass splunk tag to logging config if specified

---

Makefile

Adding a `build-windows` Makefile target.
*Testing*
`make build-windows`

adding build-windows Makefile target

---

README.md
args.go
init.go
logger/fluentd/logger.go
logger/fluentd/logger_test.go

Provide an entry to configure `fluentd-buffer-limit` in FireLens.
This is being enabled to resolve the following request: https://github.com/aws/containers-roadmap/issues/964
Help to configure buffer limit size in fluentD Log Driver
*Testing:*
Check the code with `make test` and `make lint`.

Enable buffer limit option in FireLens

---

go.mod
go.sum
logger/awslogs/logger.go
logger/buffered_logger.go
logger/common.go
logger/fluentd/logger.go
logger/splunk/logger.go

*Issue #, if available:* n/a
*Description of changes:* This change increases the number of bytes sent to CloudWatch from 16kb
to 256kb in the awslogs driver. This change also includes updates to the docker and fluent-logger-golang dependencies.
This change was tested by building the shim-logger and verifying that the resulting logs were split up into 256kb chunks from the AWS console. Existing unit tests were also ran to verify this change does not introduce any regressions.

Change the maximum number of bytes included in a CloudWatch event.

---

.github/workflows/ci.yml

The golangci-lint-action in the GitHub actions was failing because it
was auto-updating go to the latest version (1.18). Version 3 does not
re-install Go, instead it uses the currently installed version which
works with the github action.
- The golangci-lint-action was upgraded from v2 to v3.1.0.
- The setup-go-action was upgraded from v1 to v3.

Update golangci-lint-action to 3.1.0

---

logger/buffered_logger.go
logger/common.go
logger/common_test.go

Signed-off-by: Wesley Pettit <wppttt@amazon.com>
https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/issues/23
https://github.com/aws/containers-roadmap/issues/1550

fix: set partial message metadata flags in log events

---

go.mod
go.sum

In one of the recents commits we updated the docker package to 20.10.13. But the commit to skip create log streams for aws log driver was not included in that tag of docker. 
This change will patch docker 20.10.13 with the missed commit. 

Patch docker stable release with an option to skip create log stream for awslogs driver

---

go.mod
go.sum

GitHub dependabot requires to upgrade github.com/docker/distribution to
incorporate a security patch.
*Issue #, if available:* https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/security/dependabot/6
Upgraded version of github.com/docker/distribution to pull security patches.
Used the following command to upgrade:
```
go get -u github.com/docker/distribution
go mod tidy
```
Package builds successfully and all tests pass.

Upgrade dependency github.com/docker/distribution

---

.gitignore
Makefile
README.md
args.go
init.go
logger/awslogs/logger.go
logger/awslogs/logger_test.go

N/A
With this change, the shim logger can support to specify the endpoint for the aws logs.
Builds successfully and all tests pass.

Allow to configure the endpoint for awslog

---

.github/workflows/ci.yml
.gitignore
Makefile

Signed-off-by: Austin Vazquez <macedonv@amazon.com>
N/A
1. Adds Go 1.20 support.
2. Fixes an issue where Windows platform was not being tested.
3. Updates the GitHub actions/setup-go package and configures it before lint run so the appropriate version of Go is used.

Update GitHub Actions CI to address updates and issues

---

args_test.go
go.mod
go.sum

*Issue #, if available:* 
https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/issues/52
Since the implementation does not care about the order, I rewrote the test to either change the loop to make a map instead and check the contents match.

BugFix: Fix flaky unit test that conducts ordered check on unordered map -> slice conversion.

---

logger/common_test.go

Signed-off-by: Austin Vazquez <macedonv@amazon.com>
*Issue #, if available:* #32
Removes usage of deprecated io/ioutil package

Remove deprecated io/ioutil package usage

---

args.go
debug/debug_linux.go
go.mod
logger/awslogs/logger.go
logger/buffered_logger.go
logger/common.go
logger/common_linux.go
logger/common_test.go
logger/fluentd/logger.go
logger/splunk/logger.go
main.go

Signed-off-by: Austin Vazquez <macedonv@amazon.com>
*Issue #, if available:* #31
Removes direct dependency on github.com/pkg/errors and replaces functionality with built-in standard library usage of errors and fmt packages.

Remove direct dependency on github.com/pkg/errors

---

.github/workflows/ci.yaml

Running ci in non-main branch is not useful for now.

ci: limit CI on main branch only

---

.github/workflows/ci.yaml

1. Remame to "go-linter" to prevent conflict with other linters. (Will add mdlint, pr title lint later)
2. Lock compute to ubuntu-latest to simplify
3. Update versions.
4. Add comments.

ci: simplify go linter and rename it to differentiate with other linters

---

.github/workflows/ci.yaml
Makefile

Address comments of https://github.com/aws/shim-loggers-for-containerd/pull/57.

ci: several cleanup for go linter

---

.github/workflows/ci.yaml
Makefile

N/A
Go 1.21 is released. This PR adds support to the CI pipeline.

chore: add Go 1.21 support to CI

---

.github/workflows/ci.yaml
Makefile
e2e/awslogs_test.go
e2e/fluentd_test.go
e2e/main_test.go

- breaking out the 'log generation' piece out of the aws log test file into the main test file as func sendTestLogByContainerd so that it can be reused for every driver (which seems like a good idea)
- add a fluentd test that does validation
- adds fluentd to the GitHub action (note this launches a docker containerd with the fluentd server)
- adds fluentd test to makefile

ci: add fluentd basic e2e tests

---

.github/workflows/ci.yaml
Makefile
e2e/fluentd_test.go
e2e/main_test.go
e2e/splunk_test.go

The test is not perfect but can be used for basic validation because the containerd task is ran successfully with the Splunk shim logger. It is nice to validate the logs in Splunk after it. It is not straightforward to do that so opened issue to track it. https://github.com/aws/shim-loggers-for-containerd/issues/74

ci: add Splunk basic e2e tests

---

.github/workflows/ci.yaml
e2e/awslogs_test.go
scripts/start-ecs-local-endpoint

Real AWS credentials are not available in the PR workflow from forked repo. (Previous workflow failure: https://github.com/aws/shim-loggers-for-containerd/actions/runs/6204238070/job/16846048871) So switching to local stack to remove the usage of real credentials.

ci: change cloudwatch test infra from real AWS to local stack

---

logger/common_test.go

Signed-off-by: Wesley Pettit <wppttt@amazon.com>
This just ensures that if we ever break the partial metadata feature, the test will fail with a nice error on this new line, instead of failing with a null pointer exception. 

test: assert that PLogMetadata is NotNil in partial test

---

.github/workflows/ci.yaml

To fix the flaky scenario: https://github.com/aws/shim-loggers-for-containerd/actions/runs/6267460590/job/17020568425?pr=75

ci: add retry for pulling fluentd image from ECR Public

---

.github/workflows/lint-pr-title.yaml

This is for future auto release by https://github.com/googleapis/release-please.
Release-please requires the commit message to be conventional commits. 

ci: add pr title linter to enforce conventional commit

---

.github/workflows/ci.yaml

Suppress the failure caused by https://github.com/localstack/localstack/issues/9253

ci: pin the previous local stack version to fix the failure

---

.github/workflows/benchmark.yaml
Makefile
benchmark/awslogs/awslogs_test.go
benchmark/fluentd/fluentd_test.go
benchmark/splunk/splunk_test.go
e2e/awslogs_test.go
e2e/common.go
e2e/fluentd_test.go
e2e/main_test.go
e2e/splunk_test.go
scripts/start-fluentd-local-endpoint
scripts/start-localstack

add benchmarking for time and memory of sending a 1MB log
Result page: https://aws.github.io/shim-loggers-for-containerd/dev/bench/
UX improvements will come later in the gh-pages branch.

ci: add basic benchmarking

---

.golangci.yaml

N/A
This change fixes the local import check for golangci-lint goimports in CI.

ci: fix local prefix for goimports

---

logger/buffered_logger.go
logger/common.go
logger/common_linux_test.go
logger/common_test.go

*Issue #, if available:* NA
*Description of changes:* this PR is to add instrumentations when the shim logger are consuming data from the source / container pipes and sending data to the destination / the configured log drivers. Specifically we will print out the number of bytes we read from the source and the number of bytes we send to the destination every 1 minute. This can help us monitor the data workflow and check if any potential issues when routing logs.
One example about what the logs look like
```
---
| @timestamp | cmdName | message |
| --- | --- | --- |
| 2024-04-03 23:34:57.000 | shim-loggers-fo | Driver: awslogs |
| 2024-04-03 23:34:57.000 | shim-loggers-fo | Starting log streaming for non-blocking mode awslogs driver |
| 2024-04-03 23:34:57.000 | shim-loggers-fo | Starting …
```

refactor: Add instrumentations when routing logs to the log driver

---

logger/common.go

*Issue #, if available:* n/a
fixing nil error log
`    "message": "failed to send logs from pipe stdout: %!w(<nil>)",`
log the correct error variable

fix: log errors from sendLogs with correct variable in common#Start()

---

README.md

`fluentd-buffer-limit` is the limit of the number of events buffered, not bytes.

fix: update fluentd-buffer-limit documentation

---

.github/workflows/ci.yaml
e2e/awslogs_test.go

*Issue #, if available:* Build failures when merging https://github.com/aws/shim-loggers-for-containerd/pull/185
A new version of the `github.com/docker/docker` package requires the `github.com/moby/sys/blob/main/userns` package, which [uses `sync.OnceValue`](https://github.com/moby/sys/blob/main/userns/userns_linux.go). Since `sync.OnceValue` was added in go 1.21.0 ([doc link](https://pkg.go.dev/sync#OnceValue)), the tests which run on go 1.20.x are failing.

ci: bump e2e test go version and linter version

---

dev/bench/index.html

Copy and paste error from initial setup of the benchmark website from Finch
This change fixes the title on the benchmark website. i.e. https://aws.github.io/shim-loggers-for-containerd/dev/bench/

fix: benchmarks GitHub website page title

---

.github/workflows/ci.yaml

Contributors can accidentally submit git secrets to version control.
This change adds a GitHub Actions job to validate git secrets are not submitted to version control.

ci: add git secrets scanning

---

args.go
e2e/awslogs_test.go
init.go
logger/awslogs/logger.go
logger/awslogs/logger_test.go

https://github.com/aws/shim-loggers-for-containerd/issues/285
aws log driver supports an option to specify a log format sent in the header to `PutLogEvents`. 
Added an option to to allow specifying this log format in the shim config. 'json/emf' is the only supported format at the moment and this is validated by the log driver [Ref](https://github.com/moby/moby/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L787-L790)
Currently this header does not need to be specified in most regions but EMF auto detection is not launched in all aws regions requiring consumers of this shim to migrate to another driver such as Firelens. Adding the option to explicitly pass this header as an option would allow consumers to continue using EMF with the …

feat: add support for awslogs-format

---

e2e/fluentd_test.go
init.go
main.go

This PR fixes an issue with flag parsing that could cause the application to panic and adds a missing flag definition for the fluentd write timeout feature.
- **Fixed flag parsing panics**: Replaced `pflag.Parse()` with `pflag.CommandLine.Parse()` to gracefully handle flag parsing errors instead of panicking
- **Added missing fluentd write timeout flag**: Added the missing `pflag` definition for `fluentd-write-timeout` in `init.go`
- **Improved error logging**: Flag parsing errors are now properly logged before application exit
- **Problem**: `pflag.Parse()` panics on invalid flags, making debugging difficult
- **Solution**: Use `pflag.CommandLine.Parse(os.Args[1:])` which returns errors that can be handled gracefully
- **Benefit**: Better debugging experience with proper error messages …

fix - Fix flag parsing errors and add missing fluentd write timeout flag
